### ISSUE TITLE
Action failing: "retries exhausted after 6 attempts"

### ISSUE THREAD

**Issue by benknight** [w9jds/firebase-action#12]
This action started failing out of the blue about 2 weeks ago, each time the error message is:
```
Error: Task f1d5c11328b3858cac29a40918fc8b561a37dbc7ac9f9fa790dad54746afe2f8 failed: retries exhausted after 6 attempts
##[error]Docker run failed with exit code 1
```
Here's the full log: [log.txt](https://github.com/w9jds/firebase-action/files/3808091/log.txt)

**Comment by w9jds** [comment]
I need more information than this if I am going to be able to help.

**Comment by benknight** [comment]
Same, hard to determine based on Github's provided error logs. I opened this issue hoping I wasn't the only one affects. For now I can do without this action so I've simply disabled it, but if I need it again I'll try to dig deeper into this issue. For the time being maybe worth keeping open for a bit longer in case anyone else comes across it? To me it smells like a timeout.

**Comment by w9jds** [comment]
I haven't seen any activity on this so I'm going to close it.

**Comment by saranglohar** [comment]
Delete the hidden folder in you project root directory.

**.firebase/hosting.*.cache**

It works for me.

**Comment by kwalrath** [comment]
> Delete the **.firebase** hidden folder in you project root directory.

That worked for me. Thanks, @saranglohar!

**Comment by nishat-1998** [comment]
Error: Task 5a765e82b1962db980c9632cf0c2c3f594e3b63b6dd53cff6256c674e76c1448 failed: retries exhausted after 6 attempts

**Comment by ArcherEmiya05** [comment]
Still exist, is there a solution now? Deleting `.firebase` does not help.

![image](https://user-images.githubusercontent.com/38008900/117126364-3c823800-adcd-11eb-82ba-5cfb60d494d3.png)

**Comment by ireinodeDios** [comment]
Hola Tengo el mismo problema alguien me puede ayudar por favor

**Comment by w9jds** [comment]
This action is just a containerized version of `Firebase-Tools` when something like this fails it tends to be based on files missing, or configuration issues. Making sure the required firebase files, and everything are passed over to the container used for the action. I've seen issues with the token job not being the right format, missing `firebase.json`, etc. Without more info like I said above can't really give you more information than that.

**Comment by JoMaDotio** [comment]
This still happend, is there a solution?

**Comment by Ziadal3tar** [comment]
Did you get a solution?
If you get it help me pls
I have the same problem

@patbranchaud

**Comment by patbranchaud** [comment]
> Did you get a solution? If you get it help me pls I have the same problem
> 
> @patbranchaud

Updated Firebase the latest version and changed the uploadQueue default concurrency to 10 instead of 200
REFER TO THIS : https://github.com/firebase/firebase-tools/issues/4279
