### ISSUE TITLE
Why is Firebase Admin role required?

### ISSUE THREAD

**Issue by gustavohenke** [w9jds/firebase-action#121]
Hey 👋  Thanks for this helpful action!
I've started using it today to deploy Firestore indices and rules.
To begin with, I've created a service account with the `Cloud Datastore Index Admin` and `Firebase Rules Admin` roles, then downloaded the key and tried it locally, which worked:

```
$ GOOGLE_APPLICATION_CREDENTIALS=key.json yarn firebase deploy --only firestore
yarn run v1.22.11
$ /Users/gustavohenke/Projects/my-project-id/node_modules/.bin/firebase deploy --only firestore

=== Deploying to 'my-project-id'...

i  deploying firestore
i  firestore: reading indexes from config/firebase/firestore.indexes.json...
i  cloud.firestore: checking config/firebase/firestore.rules for compilation errors...
✔  cloud.firestore: rules file config/firebase/firestore.rules compiled successfully
✔  firestore: deployed indexes in config/firebase/firestore.indexes.json successfully
i  firestore: latest version of config/firebase/firestore.rules already up to date, skipping upload...
✔  firestore: released rules config/firebase/firestore.rules to cloud.firestore

✔  Deploy complete!
```

However, when I created a workflow that contained the below step, it didn't work, like there's no permission? 

```yaml
- uses: w9jds/firebase-action@master
  with:
    args: deploy --only firestore
  env:
    PROJECT_ID: wharft-app
    GCP_SA_KEY: ${{ secrets.FIREBASE_FIRESTORE_SERVICE_ACCOUNT }}
```

Error:

> Storing GCP_SA_KEY in /opt/gcp_key.json
> Exporting GOOGLE_APPLICATION_CREDENTIALS=/opt/gcp_key.json
> setting firebase project to my-project-id
> Error: Invalid project selection, please verify project my-project-id exists and you have access.

Seems like I can add `Firebase admin` role and rerun the workflow and it'll work, but that's more than I need to deploy rule changes.
Looking at the source code of the action, there isn't anything too wild that caught my attention why it'd fail?

**Comment by w9jds** [comment]
I've updated the `README` specifying that if you use `PROJECT_ID` your service account needs `Firebase View` permissions. Thank you!
