### ISSUE TITLE
Latest and v2.1.1 will be failed deploying

### ISSUE THREAD

**Issue by camelmasa** [w9jds/firebase-action#132]
v2.1.1 outputs `Error response from daemon: manifest for w9jds/firebase-action:2.1.1 not found: manifest unknown: manifest unknown`.

Maybe, Latest commit fixed that https://github.com/w9jds/firebase-action/commit/da2487890c3fce98fab19ad9381c83a10d12aa81. But, Latest version isn't included the commit.

We are avoiding issue using v2.1.0 for now.
Like following.

```
w9jds/firebase-action@v2.1.0
```

**Comment by w9jds** [comment]
This is being fixed right now, I missed the `v` in the docker string. Sorry about that! Should be resolved in `v2.1.2` being built right now.

**Comment by camelmasa** [comment]
Thanks for your contributions 🤗 We are using the Actions every days.

**Comment by w9jds** [comment]
Glad it helps!! Sorry again for the issue, hopefully it's all fixed now.
