### ISSUE TITLE
PROJECT_PATH not finding firebase.json

### ISSUE THREAD

**Issue by vemuez** [w9jds/firebase-action#14]
**Error that im getting**

![image](https://user-images.githubusercontent.com/9627828/68532394-99a24800-0314-11ea-98c5-bc9f1444eed2.png)
---

**My step configuration, they all pass except for the deploy**

![image](https://user-images.githubusercontent.com/9627828/68532433-f6056780-0314-11ea-89c5-d77c199ae521.png)
---
**Root of my project...**

![image](https://user-images.githubusercontent.com/9627828/68532412-ca827d00-0314-11ea-9920-5136b5b32687.png)
---
**Inside ./Api**
![image](https://user-images.githubusercontent.com/9627828/68532453-22b97f00-0315-11ea-8dc9-1a4132d2489d.png)

**Comment by w9jds** [comment]
Could you try using `w9jds/firebase-action@master` I believe that `v1.1.0` is the version that doesn't work properly. If that works I can create a new release so you can set it to a proper version that works.

**Comment by vemuez** [comment]
It works perfectly!

**Comment by w9jds** [comment]
Fantastic! I created a new release of `1.2.0`
