### ISSUE TITLE
Error when using functions:config:set as args in 2.2.1 version

### ISSUE THREAD

**Issue by rafael-celebreak** [w9jds/firebase-action#141]
Hello!

Starting on version 2.2.1, I'm getting an error when trying to update firebase env. The output doesn't report any errors, but the task fails (you can find the content of the output [here](https://gist.github.com/rafael-celebreak/8d308e1b92cdf19020519d9ad87824cd#file-firebase_github_output-txt)).

[Here](https://gist.github.com/rafael-celebreak/f647af93e3d4c344b77e1f6d7bc1f395) you can see the content of the workflow file (project specific information is hidden).

If I modify the workflow file to use version 2.2.0 (uses: docker://w9jds/firebase-action:v2.2.0), it works properly.

Functions deployment is not affected by this, only firebase environment updates.

Thank you very much for your attention, and please let me know if I can help in any way here!

Rafael

**Comment by weilinzung** [comment]
Failed for us as well, but no error log at all.

**Comment by jrosesol** [comment]
Me too! please please help

**Comment by ygordanniel** [comment]
For all of you having trouble with latest version, use the last stable version, e.g: `w9jds/firebase-action:v2.2.0`

So instead of

```
uses: w9jds/firebase-action@master
```

You would do

```
docker://w9jds/firebase-action:v2.2.0
```

**Comment by JulianOcampo** [comment]
this does not work
`uses: docker://w9jds/firebase-action:v2.2.0`

**Comment by w9jds** [comment]
Let the build finish and master should work again for you, I removed action exports.
