### ISSUE TITLE
How can i check the firebase tools version ?

### ISSUE THREAD

**Issue by johnico** [w9jds/firebase-action#146]
I would like to see or to print the ftools version + node version 
is it possible?

i see in the docker file that we have 

``` npm i -g firebase-tools@10.9.2```

can we upgrade it to 11.4 ?

**Comment by indicava** [comment]
I second this. I am running into errors on function deployment which have been resolved in 11.4.2 (11.5 is already out).

See here:
https://github.com/firebase/firebase-tools/issues/4266

**Comment by w9jds** [comment]
I just updated the firebase-tools version to v11.5.0, update to pull latest or point to v11.5.0 I'm going to use the firebase version for the version base going forward to make it easier to tell which version it is. Otherwise, you just check the DockerFile.
