### ISSUE TITLE
Error with new image

### ISSUE THREAD

**Issue by tavishigupta** [w9jds/firebase-action#147]
Hi! Our CI/CD broke, which uses this package. We get this error:

```
Error: w9jds/firebase-action/master/action.yaml: 
Error: w9jds/firebase-action/master/action.yaml: (Line: 15, Col: 10, Idx: 298) - (Line: 16, Col: 1, Idx: 338): While scanning a quoted scalar, find unexpected end of stream. 
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected. at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription) at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile) 
Error: Fail to load w9jds/firebase-action/master/action.yaml
```
The CI/CD worked 13 hours ago. We ran it again 10 minutes ago and it's broken. Let me know if you want more information!

**Comment by dogyun-wildseed** [comment]
I have same issue

**Comment by ciatph** [comment]
Same here 😄 I'm attaching a screenshot for reference. Let us know if we need to do extra steps regarding the latest update. Thanks! 

![fb-error](https://user-images.githubusercontent.com/30580083/183813821-47bdaa7f-3774-4ab1-bc69-c76b80f40cf2.PNG)

**Comment by w9jds** [comment]
Working on pushing a fix now, sorry about that.

**Comment by w9jds** [comment]
This should be fixed now, sorry for the inconvenience. Try running your build again!
