### ISSUE TITLE
Java Version

### ISSUE THREAD

**Issue by r-dev-limited** [w9jds/firebase-action#149]
New version of firebase tools require Java>11

Please change it in dockerfile

**Comment by w9jds** [comment]
Could you please try pointing to `uses: docker://w9jds/firebase-action:master` and see if that fixes it for you. I moved over to openJDK 11 and want to make sure it fixes the emulators for you before I update the image. I personally don't have anything setup to test this at this moment 😅

Thanks

**Comment by FannyDemey** [comment]
@w9jds FYI it works for me !  thanks ! let me know when I can switch back to the original image

**Comment by w9jds** [comment]
I'll update the v11.5.0 image later today for you and let you know when it's live. Thanks for confirming that it worked!

**Comment by w9jds** [comment]
Sorry for the delay, this should be available in the latest release of the action now (v11.5.0)
