### ISSUE TITLE
Firebase Deploy not work normally on v11.5.0

### ISSUE THREAD

**Issue by kboy-silvergym** [w9jds/firebase-action#150]
## Problem

When I use v11.5.0, the error has shown. ↓↓

```
Authenticating with `FIREBASE_TOKEN` is deprecated and will be removed in a future major version of `firebase-tools`. Instead, use a service account key with `GOOGLE_APPLICATION_CREDENTIALS`: https://cloud.google.com/docs/authentication/getting-started
```

And when hosting to Firebase Hosting, the page turned to white screen.

## Workaround
When I back to v2.2.2, the action work well.

That's it.

**Comment by kboy-silvergym** [comment]
Maybe this change occurred something bad influence.

https://github.com/w9jds/firebase-action/commit/e268f4eac3cc6630102230f3d610b4299f9e23b4

**Comment by w9jds** [comment]
Yes v2.2.2 uses an older version of `firebase-tools` This is most likely related to the major changes they are making to their CLI. I will have to look into this as I use hosting with my action as well.

**Comment by w9jds** [comment]
Haven't heard anything since the latest versions so closing this.
