### ISSUE TITLE
Response not accessible 

### ISSUE THREAD

**Issue by ashish-ncompass** [w9jds/firebase-action#152]
@w9jds 
How to access the firebase command execution response or output in another step or job. I tried with `${{ steps.<id>.outputs.response }}`.
But it doesn't seem to be working, though it is mentioned in README file.
Is this something new to be added as a feature??

**Comment by w9jds** [comment]
Yeah, sadly this was removed due to it breaking a lot of builds (outputs never coming out, especially when errors happened). I forgot to remove that from the README, sorry about that.
