### ISSUE TITLE
How to deploy only firestore or storage?

### ISSUE THREAD

**Issue by piggy0713** [w9jds/firebase-action#159]
I tried to use this GitHub action for deploying firestore and storage, and I got an error saying ```HTTP Error: 403, The caller does not have permission`` I am not sure what permission I need for firestore or storage. Also If I try to deploy everything with ```args: deploy```  it gave me the same error.  Any help will be really appreciated.

**Comment by asithade** [comment]
I'm getting the same error too. I'm not sure what permissions are needed to have this deploy.

**Comment by w9jds** [comment]
It sounds like the service account, or token you provided doesn't have permissions to do that deployment.

**Comment by piggy0713** [comment]
@w9jds I gave service acount ```Cloud Functions Developer``` , ```Cloud Scheduler Admin```, ```Service Account User```, ```Firebase Hosting Admin``` and ``` Viewer``` permission, not sure which permission is needed for those asset.

**Comment by gorden0929** [comment]
For firestore index you can use this role: Cloud Datastore Index Admin
For firestore rules and storage rules you can use this role: Firebase Rules Admin

**Comment by cjwhitsitt** [comment]
> For firestore index you can use this role: `Cloud Datastore Index Admin` For firestore rules and storage rules you can use this role: `Firebase Rules Admin`

This worked for me. I'll make a PR with updates to the documentation
