### ISSUE TITLE
Error: Bolt not installed, run npm install -g firebase-bolt

### ISSUE THREAD

**Issue by anantakrishna** [w9jds/firebase-action#16]
I'm getting this on deployment.

```
Error: Bolt not installed, run npm install -g firebase-bolt
##[error]Docker run failed with exit code 1
```

Whereas the `firebase-bolt` is installed globally. 

My workflow file is https://github.com/PureBhaktiArchive/audioseva/blob/deployment/.github/workflows/deployment.yml.

**Comment by w9jds** [comment]
Being installed globally does nothing for building inside a container on the cloud, you need to include the install inside of your project. This has nothing to do with the action, but more with the project you are trying to build.

**Comment by anantakrishna** [comment]
Yes I have figured this out after looking at the source code of your
action. Finally I have just installed a firebase tools package globally and
used directly instead of this action.
