### ISSUE TITLE
Cleaning up build files in Cloud Functions deployments

### ISSUE THREAD

**Issue by ViloCat** [w9jds/firebase-action#161]
I am deploying cloud functions and everything works perfectly except for one thing: it seems that the build images are not cleaned properly. I do not have this warning when deploying from my machine, so I guess there could be some problem with the Service Account token... Any ideas?

Thanks!

```
i  functions: cleaning up build files...
⚠  functions: Unhandled error cleaning up build images. This could result in a small monthly bill if not corrected. You can attempt to delete these images by redeploying or you can delete them manually at
	https://console.cloud.google.com/artifacts/docker/*******
	https://console.cloud.google.com/gcr/images/*******

✔  Deploy complete!
```

**Comment by w9jds** [comment]
It sounds like the `firebase.json` file doesn't have exclude/include setup properly and it's picking up other things inside of your build pipeline. This wouldn't be related to the action in any particular way.
