### ISSUE TITLE
[Documentation] Functions runWith secrets GCP_SA_KEY need permission Secret Manager Admin

### ISSUE THREAD

**Issue by gorden0929** [w9jds/firebase-action#164]
If the cloud functions has configure runWith secrets, the service account has to include role Secret Manager Admin to access the secrets.

I got the following error when I add role Secret Manager Viewer
```
Error: Failed to validate secret versions:
- FirebaseError HTTP Error: 403, Permission 'secretmanager.versions.get' denied for resource 'projects/<PROJECT_NAME>/secrets/TOKEN/versions/latest' (or it may not exist).
```

and this error when I add role Secret Manager Secret Accessor
```
Error: HTTP Error: 403, Permission 'secretmanager.secrets.setIamPolicy' denied for resource 'projects/<PROJECT_NAME>/secrets/TOKEN' (or it may not exist).
```

I also got this error if I add role Cloud Functions Developer
```
Error: Missing required permission on project <PROJECT_NAME> to deploy new HTTPS functions. The permission cloudfunctions.functions.setIamPolicy is required to deploy the following functions:

- webhooks

To address this error, please ask a project Owner to assign your account the "Cloud Functions Admin" role at the following URL:
```

Just wondering is there any role lower than Secret Manager Admin can be used because Secret Manager Admin is quite overpowered.

**Comment by w9jds** [comment]
Another user has recently updated the README to help list the kinds of roles you need for each kind of functionality.
