### ISSUE TITLE
Cannot deploy a web framework to hosting because the experiment webframeworks is not enabled

### ISSUE THREAD

**Issue by waylun** [w9jds/firebase-action#165]
Got this on recent deployment
`Error: Cannot deploy a web framework to hosting because the experiment webframeworks is not enabled. To enable webframeworks run firebase experiments:enable webframeworks`

The command I use for deploy is:
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting --project myapp
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

**Comment by waylun** [comment]
I just figure out by my own can use
`  - uses: FirebaseExtended/action-hosting-deploy@v0
     with:
       # ...
     env:
       FIREBASE_CLI_EXPERIMENTS: webframeworks`

**Comment by w9jds** [comment]
You can also use my `w9jds/setup-firebase` this allows you to run multiple commands in a single workflow as it sets up firebase for the entire job making it custom for each run. This is a docker action so unless doing this inside of the container for everyone it won't work.
