### ISSUE TITLE
Service Account Priviledges for Firestore Rules and Index Deployment

### ISSUE THREAD

**Issue by georg-schwarz** [w9jds/firebase-action#166]
I followed your documentation and provider the following roles to the service account:
![image](https://user-images.githubusercontent.com/28054628/204092995-9a3bc70c-dab8-4f6a-812a-83324a067d4f.png)

However, when deploying with flags ` --only firestore:rules` and `--only firestore:indexes`, I get a 403:
`Error: HTTP Error: 403, The caller does not have permission.`

Any ideas what I am missing?

**Comment by cjwhitsitt** [comment]
You might try adding the roles mentioned in this comment: https://github.com/w9jds/firebase-action/issues/159#issuecomment-1340217898
