### ISSUE TITLE
Actions for deployment firebase cloud functions

### ISSUE THREAD

**Issue by polRk** [w9jds/firebase-action#2]
Can u add support for deployment cloud functions ?
Deploy only modified functions, not all.
And support typescript.

**Comment by w9jds** [comment]
1: This alread supports deploying cloud functions. This contains the whole firebase-tools system inside of it, so you just make you config like this:

```
action "Deploy Production Site" {
  uses = "w9jds/firebase-action@master"
  args = "deploy --only functions"
  env = {
    PROJECT_ID = "new-eden-storage-a5c23"
  }
  secrets = ["FIREBASE_TOKEN"]
}
```

2: If you want to only deploy modified functions then you would need a seperate action to filter your workflow that only moves on to using a firebase-action if the functions folder has been modified.

3: It already supports typescript, firebase-tools doesn't care what you write things in. As long as it is setup correctly it will deploy it.
