### ISSUE TITLE
Node.js version 16 no longer supported.

### ISSUE THREAD

**Issue by xylo04** [w9jds/firebase-action#204]
[Starting today](https://github.com/RMHAM/open-ics/actions/runs/6869893908), I'm getting the message:

```
Node.js version v16.16.0 detected.
The Angular CLI requires a minimum Node.js version of v18.13.
```

**Comment by w9jds** [comment]
I'm not sure if this will affect things around firebase functions as I think they are still mainly Node 16. This seems to be related to an experimental framework support for Firebase Hosting which needs to use other CLIs to properly compile your project and is directly related to Angular CLI not Firebase CLI. Out of curiosity, if you use `setup-node` and `setup-firebase` instead to specify specific versions, does that work?

**Comment by xylo04** [comment]
I'm [using setup-node](https://github.com/RMHAM/open-ics/actions/runs/6869893908/workflow#L18) with node 18, but that doesn't seem to affect the node version inside the action's container.

I'll also note that Node 16 is [end of life](https://nodejs.org/en/blog/announcements/nodejs16-eol) and no longer maintained.

**Comment by artanisdesign** [comment]
Hi!

Same issue here:

`error functions@1.0.0: The engine "node" is incompatible with this module. Expected version "18". Got "16.16.0"
error Found incompatible module.`

my functions are on 18, also setup node is on 18. still this step wanna use 16 :/

**Comment by w9jds** [comment]
`setup-node` does nothing for this as it's a docker action, that is why I suggested trying my `setup-firebase` that is a revamp of this action but more flexible and powerful. I will take a look at merging this in.

**Comment by xylo04** [comment]
I'm open to trying your other action https://github.com/w9jds/setup-firebase. I was a little worried because it hasn't received any updates in a while, but I'll give it a shot.

**Comment by w9jds** [comment]
The nice thing about that one, is that it doesn't need updates. You tell it what version you want to use and it just pulls it as needed. It's why I created it, it allows you to specify the Firebase-tools version, and use things like `setup-java` and `setup-node` so you get way more flexibility.
