### ISSUE TITLE
Pulling @master results in error. is 12.9.0 out?

### ISSUE THREAD

**Issue by MartinSandstromRimsbo** [w9jds/firebase-action#207]
My github action just stopped working, I have made no changes.  

- uses: w9jds/firebase-action@master

Error:
 
/usr/bin/docker pull w9jds/firebase-action:v12.9.0
Error response from daemon: manifest for w9jds/firebase-action:v12.9.0 not found: manifest unknown: manifest unknown
Warning: Docker pull failed with exit code 1, back off 8.[6](https://github.com/Spotterfish/audiopostr-web/actions/runs/6874867006/job/18697340368#step:2:6)34 seconds before retry.
/usr/bin/docker pull w9jds/firebase-action:v12.9.0
Error response from daemon: manifest for w9jds/firebase-action:v12.9.0 not found: manifest unknown: manifest unknown

Error: Docker pull failed with exit code 1

Any ideas?

**Comment by maylorsan** [comment]
same issue

**Comment by zilker** [comment]
The same thing happened to me.

**Comment by irmakcosarsahna** [comment]
same issue

**Comment by javibrico** [comment]
same issue

**Comment by Agusnez** [comment]
Same issue in our team. Looks like the 12.9 version is not listed as a release, but the PR was merged an hour ago, so maybe they are tagging it already but takes time for the change to propagate.

In the meantime pulling the 12.8 version instead of master will do the trick!

**Comment by waylun** [comment]
same issue

**Comment by peter-palmer** [comment]
I'm getting the same issue 👀

**Comment by peter-palmer** [comment]
Hello everyone,

I've come across a temporary solution for the issue we've been experiencing with the `w9jds/firebase-action` when trying to deploy functions to Firebase using GitHub Actions.

After encountering errors with the latest version and the version `12.9.0` not being found, I've successfully used version `v12.8.0`. It seems this version is stable and works as expected for the time being. Here's the updated workflow configuration:

```yaml
# Deploying the functions to Firebase
- name: Deploy to Firebase
  uses: w9jds/firebase-action@v12.8.0
  with:
    args: deploy --only functions
  env:
    FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
```

This configuration has worked in my case. If you're facing similar issues, you might want to give this a try. Remember to adjust your workflow file accordingly.

Also, it's always a good idea to keep an eye on the repository for any official fixes or updates. Let's hope for a permanent solution soon.

**Comment by Hovmark** [comment]
Same issue here

**Comment by elmehdibm** [comment]
Same issue here

**Comment by btryder** [comment]
yup master pull failed for me, used the suggested pinning to 12.8.0

**Comment by ecam900** [comment]
Same issue - pinned 12.8.0

**Comment by tudorsibiu90** [comment]
tag seems to be missing :P

**Comment by xephtar** [comment]
Same issue here, back to 12.8.0 tag

**Comment by irmakcosarsahna** [comment]
> Same issue in our team. Looks like the 12.9 version is not listed as a release, but the PR was merged an hour ago, so maybe they are tagging it already but takes time for the change to propagate.
> 
> In the meantime pulling the 12.8 version instead of master will do the trick!

Thanks it worked.

**Comment by w9jds** [comment]
The tag should be properly built now, apologies for the issue. This is one of the reasons I was trying to move away from the docker actions. 😅

**Comment by Psycarlo** [comment]
@w9jds Any news on `firestore:rules` and `storage` not deploying?

```
uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions,firestore:rules,firestore:indexes,storage
```
