### ISSUE TITLE
Doesn't work for deploying python firebase functions

### ISSUE THREAD

**Issue by MaitreyaBuddha** [w9jds/firebase-action#209]
```
Error: Failed to find location of Firebase Functions SDK: Missing virtual environment at venv directory. Did you forget to run 'python3.11 -m venv venv'?
```

This makes sense since we're running in a nodejs docker. I'm not sure we would want to make a universal docker image for both because of how heavy it would get. I'm considering forking to firebase-action-python for this purpose, but I haven't figured out a lightweight way to get firebase and python on the same image yet.

**Comment by w9jds** [comment]
Give a look at `setup-firebase` that action should be able to do what you are looking for. That one will allow you to use things like `setup-python` and it will then have your systems you are looking for. It would also end up being faster as it doesn't pull docker images.
