### ISSUE TITLE
consider run on other working-directory

### ISSUE THREAD

**Issue by comfuture** [w9jds/firebase-action#21]
Hi,

I'm using firebase functions partially in my project's sub directory `./firebase`
So, I need to run `firebase deploy --only functions` in `./firebase` directory.

can you add `working-directory` argument to this action like plain `run` command?

Best,

**Comment by w9jds** [comment]
This already exists:

```PROJECT_PATH - Optional. The path to firebase.json if it doesn't exist at the root of your repository. e.g. ./my-app```

**Comment by nearwood** [comment]
@w9jds I have a very similar issue:

webapp based at `./`
functions based at `./functions`
`firebase.json` is also in the root: `./firebase.json`

When running `deploy --only functions --force`, even with `PROJECT_PATH: ./functions` it runs eslint and uses the wrong package.json (the one from the webapp). I've tried modifying my firebase.json the following ways:

```
"functions": {
    "predeploy": [
      "npm --prefix ./functions run lint"
    ]
  }
```
```
"functions": {
    "predeploy": [
      "npm --prefix ./functions run lint -- ./functions/"
    ]
  }
```
```
"functions": {
    "predeploy": [
      "cd functions && npm run lint"
    ]
  }
```

I thought this is more of an eslint/npm issue but it runs fine locally with `npm --prefix ./functions run lint`, from the project root.

**Comment by nearwood** [comment]
Alright, finally found a way to make it work locally and on CI:

```
"functions": {
    "predeploy": [
      "npm --prefix ./functions run lint -- --config ./.eslintrc.json"
    ]
  }
```

It also works whether you are in the `functions` subdirectory or the root. Yay. No idea why eslint keep picking up the wrong config. Probably an env var or something on the CI server.
