### ISSUE TITLE
New v13.0.1 docker image is unavailable

### ISSUE THREAD

**Issue by Athelian** [w9jds/firebase-action#212]
```
Download action repository 'w9jds/firebase-action@master' (SHA:40d0dffe78981f0f66d1c704a64fb4ba8b60df20)
```
```
Pull down action image 'w9jds/firebase-action:v1[3](https://github.com/zenportinc/web-app/actions/runs/7137315266/job/19437159822#step:2:3).0.1'
  /usr/bin/docker pull w9jds/firebase-action:v13.0.1
  Error response from daemon: manifest for w9jds/firebase-action:v13.0.1 not found: manifest unknown: manifest unknown
```

I temporarily fixed my pipeline by changing to `w9jds/firebase-action@v12.9.0`

**Comment by ewenmic** [comment]
I'm having the same issue. All my Github Actions integrations with _**w9jds/firebase-action@master**_ are currently broken.

**Comment by mickrip** [comment]
Yep, I second this. The v13.0.1 tag no longer exists on docker hub.

**Comment by w9jds** [comment]
Yeah, looks like the tag action didn't properly create a docker image and deploy it to the hub.

**Comment by w9jds** [comment]
Should be fixed now, give it another go. Apologies for the issues, trying out a new automated updater.

**Comment by nubeapps** [comment]
Hi! Seems to be failing again. Also trying to use version 12.9.0 is failing on my side.

**Comment by codeinearts** [comment]
@w9jds FYI this just happened again for v13.4.0 haha

**Comment by jhonatan89** [comment]
@w9jds FYI it is happening with the last version v13.5.1

**Comment by bobbyscharmann** [comment]
Same issue here

**Comment by Engineersticity** [comment]
@w9jds This is happening for the latest v13.5.2 as well

<img width="910" alt="image" src="https://github.com/w9jds/firebase-action/assets/37952208/b3e411b3-449d-4967-8037-6031b43054a9">

**Comment by brimac1634** [comment]
This is occurring with the latest v13.6.1

It appears this version is not aligned with any available docker image tag :13.6.1

**Comment by bobbyscharmann** [comment]
Is it a best practice to tie to a specific version here since @master is unreliable?

**Comment by xA6V5x** [comment]
Hi! Seems to be failing again. Also trying to use version 13.7.4 is failing on my 
![image_2024-04-24_134220304](https://github.com/w9jds/firebase-action/assets/96439189/1dd2df91-9d04-4397-8be8-440df7b1aa0a)
side.

**Comment by skykit-jonalden** [comment]
@master is continuing to fail. Is there a known working version?

**Comment by ezequieltejada** [comment]
Same here 😢

**Comment by shristov-Monterway** [comment]
same

**Comment by skykit-jonalden** [comment]
I downgraded to v12.9.0 and it is working for me. master seems to be unreliable.

**Comment by Joaoasbittencourt** [comment]
Same here!
