### ISSUE TITLE
New v13.1.0 docker image is unavailable

### ISSUE THREAD

**Issue by quieterkali** [w9jds/firebase-action#217]
```
Pull down action image 'w9jds/firebase-action:v13.1.0'

/usr/bin/docker pull w9jds/firebase-action:v13.1.0
  Error response from daemon: manifest for w9jds/firebase-action:v13.1.0 not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 4.249 seconds before retry.
  /usr/bin/docker pull w9jds/firebase-action:v13.1.0
  Error response from daemon: manifest for w9jds/firebase-action:v13.1.0 not found: manifest unknown: manifest unknown
Error: Docker pull failed with exit code 1
```

**Comment by jserrano-alq** [comment]
Output from Github Actions

`
Warning: Docker pull failed with exit code 1, back off 9.874 seconds before retry.
  /usr/bin/docker pull w9jds/firebase-action:v13.1.0
  Error response from daemon: manifest for w9jds/firebase-action:v13.1.0 not found: manifest unknown: manifest unknown
`

**Comment by wonjae-codecabin** [comment]
Same error.

**Comment by Raghavsharma2001** [comment]
Hey guys, I'm experiencing the same issue. For the time being, until it's resolved, I've rolled back to a previous version in the workflow file, which fixed the issue for now. 

<img width="489" alt="Screenshot 2024-01-25 at 1 39 23 pm" src="https://github.com/w9jds/firebase-action/assets/92421172/c3514c7c-e0eb-4ffd-aaa3-4727f38775d3">

**Comment by nghiatran0401** [comment]
Same error

<img width="1056" alt="Screenshot 2024-01-25 at 11 53 12" src="https://github.com/w9jds/firebase-action/assets/57965005/35d0dfed-af4b-4056-b70f-2832f860ec5e">

**Comment by Mihaildimitrov** [comment]
Same error 
Pull down action image 'w9jds/firebase-action:v1***.1.0'
Error: Docker pull failed with exit code 1

**Comment by aravindvakil** [comment]
> Hey guys, I'm experiencing the same issue. For the time being, until it's resolved, I've rolled back to a previous version in the workflow file, which fixed the issue for now.
> 
> <img alt="Screenshot 2024-01-25 at 1 39 23 pm" width="489" src="https://private-user-images.githubusercontent.com/92421172/299529807-c3514c7c-e0eb-4ffd-aaa3-4727f38775d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMDQ2OTksIm5iZiI6MTcwNjIwNDM5OSwicGF0aCI6Ii85MjQyMTE3Mi8yOTk1Mjk4MDctYzM1MTRjN2MtZTBlYi00ZmZkLWFhYTMtNDcyN2YzODc3NWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE3Mzk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OTExNGI3ZDgyNjQwOWM4NGI3NTc2MzIyMTliMjU5ZGU2NWZiNzZjNjg5YjA5MWYzYjNhMTEwM2U1ZTkyODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QkQmkgDA7X9w_x_HNHpUCAY5bWl4h5QiIRzRlyhz5zs">

Thanks @Raghavsharma2001. It worked.

**Comment by w9jds** [comment]
Apologies. The automated Docker build when Firebase-Tools works fine, but it seems when it automatically creates a new Release and Tag it doesn't properly trigger my other build that creates the docker image. I had to manually delete the release and tag then recreate them to trigger it properly so it should be available again.
