### ISSUE TITLE
w9jds/firebase-action:v13.3.1 not found

### ISSUE THREAD

**Issue by mickrip** [w9jds/firebase-action#222]
Error response from daemon: manifest for w9jds/firebase-action:v13.3.1 not found: manifest unknown: manifest unknown

Might want to complete your upgrade :)

**Comment by taishjason** [comment]
I am try with w9jds/firebase-action@v12.9.0 

It solve manuifest unknown but new error found.

**Comment by ssagli** [comment]
`w9jds/firebase-action:v13.4.0 not found` for me

**Comment by taishjason** [comment]
My latest workable is using `w9jds/firebase-action@v13.3.0`
