### ISSUE TITLE
Master branch is not working

### ISSUE THREAD

**Issue by SuperBluestar** [w9jds/firebase-action#223]
Hi, @w9jds 
I am using this module for firebase deployment in github action.
The action script was working and i am using master branch.
But after latest updating, it's not working.
I have attached the screenshot.

![image](https://github.com/w9jds/firebase-action/assets/81801796/f4796e80-890f-4280-ab93-4eec489d81d3)

**Comment by w9jds** [comment]
Fixed had to recreate the release as the automated creation of the tag still isn't triggering the GitHub action properly.
