### ISSUE TITLE
Pull down action image 'w9jds/firebase-action:v13.7.0' not found

### ISSUE THREAD

**Issue by adityakitabisa** [w9jds/firebase-action#227]
got this error

`Pull down action image 'w9jds/firebase-action:v13.7.0'
  /usr/local/bin/docker pull w9jds/firebase-action:v13.7.0
  Error response from daemon: manifest for w9jds/firebase-action:v13.7.0 not found: manifest unknown: manifest unknown`

**Comment by minjan** [comment]
same error `firebase-action:v13.7.0 not found: manifest unknown: manifest unknown`

**Comment by JesusMF23** [comment]
same happening here

**Comment by davidnext** [comment]
+1

**Comment by guilhermehrcosta** [comment]
+1

**Comment by guilhermehrcosta** [comment]
Use this:


uses: w9jds/firebase-action@v13.4.0

https://github.com/w9jds/firebase-action/issues/226#issuecomment-2034155669
