### ISSUE TITLE
Error Docker manifest v13.7.5

### ISSUE THREAD

**Issue by mickrip** [w9jds/firebase-action#233]
Here we go again.

```
Error response from daemon: manifest for w9jds/firebase-action:v13.7.5 not found: manifest unknown: manifest unknown
```

I don't feel great about complaining about open source software, but every time there's an upgrade, we have a problem like this. Can we collectively figure this out and solve the 'upgrade problem' once and for all?

**Comment by daneren2005** [comment]
I'm confused why it isn't running the docker push.  Looking at the action it says to trigger off of master: https://github.com/w9jds/firebase-action/blob/master/.github/workflows/build-publish.yaml

**Comment by JaredEzz** [comment]
I'm just going to ignore updates for this. The older versions work fine and I, too, am tired of this breaking

**Comment by w9jds** [comment]
They have limited how GitHub actions trigger, so it automates the update of firebase-tools but the system that publishes a new container isn't triggering. I'm in the process of fixing it, but I'm in the middle of a move so I should get to it soon. Apologies for all the issues!

**Comment by ENT108** [comment]
> They have limited how GitHub actions trigger, so it automates the update of firebase-tools but the system that publishes a new container isn't triggering. I'm in the process of fixing it, but I'm in the middle of a move so I should get to it soon. Apologies for all the issues!

Any progress maybe? 🤓

**Comment by w9jds** [comment]
I just pushed an update, hopefully this should make it so it properly published a new container when a new version is found and updated. I'll keep an eye on the next release and hope it is more reliable.

**Comment by w9jds** [comment]
I have figured out the issue with the docker deployment, I'm currently looking into it not possibly using the correct version of the repo but it shouldn't fail to publish an image anymore.
