### ISSUE TITLE
Error docker manifest 13.8.0

### ISSUE THREAD

**Issue by uday-ncompass** [w9jds/firebase-action#234]
Hello,

I have this error in my Github action. Can anyone look into this issue

![image](https://github.com/w9jds/firebase-action/assets/105187981/87ee4c31-cb73-4bdd-9ed1-660d0c1fff4d)

**Comment by rajpatelfreelancer** [comment]
Yes I also got same error, can you guide me how can I resolve that?

**Comment by uday-ncompass** [comment]
> Yes I also got same error, can you guide me how can I resolve that?

For now, I've temporarily reverted to version 13.7.5 of the w9jds/firebase-action instead of using the latest version from the master branch.

**Comment by rajpatelfreelancer** [comment]
If I use static version then its throws this error

Error: Unable to resolve action `w9jds/firebase-action@13.7.5`, unable to find version `13.7.5`


I did using like below
        uses: w9jds/firebase-action@13.7.5

**Comment by uday-ncompass** [comment]
> If I use static version then its throws this error
> 
> Error: Unable to resolve action `w9jds/firebase-action@13.7.5`, unable to find version `13.7.5`
> 
> I did using like below uses: w9jds/firebase-action@13.7.5

you missed 'v' before the number use w9jds/firebase-action@v13.7.5

**Comment by rajpatelfreelancer** [comment]
Oh, Got it. Thanks Its working
