### ISSUE TITLE
weekly actions bot "bumping" the version causes docker manifest error 

### ISSUE THREAD

**Issue by pinchy** [w9jds/firebase-action#235]
The weekly "bump" to the version results in a docker manifest error each time:

```
  /usr/bin/docker pull w9jds/firebase-action:v13.8.1
  Error response from daemon: manifest for w9jds/firebase-action:v13.8.1 not found: manifest unknown: manifest unknown
```
This is the same root cause for issues https://github.com/w9jds/firebase-action/issues/233 and https://github.com/w9jds/firebase-action/issues/232

I can't see a reason to have this version bump, there doesn't appear to be any material changes aside from the version text incrementing each time:
https://github.com/w9jds/firebase-action/compare/v13.7.0...v13.8.1

Could we disable the weekly version bump bot until GitHub actions is a bit more stable perhaps?

**Comment by ENT108** [comment]
same here

**Comment by ENT108** [comment]
![Screenshot 2024-05-09 at 10 10 48](https://github.com/w9jds/firebase-action/assets/25681316/03d4404f-90cb-475d-abd7-958f050b23d8)

downgrading is not helping event though dicker imgae is present:

https://hub.docker.com/layers/w9jds/firebase-action/v13.8.0/images/sha256-471231ad74a43fbdbaa89cc71376df102a5cbf5b8f31b084ffd847c3ae0e978f?context=explore

**Comment by pinchy** [comment]
Failed again on the version bot bump to 13.10.0

```12s
Pull down action image 'w9jds/firebase-action:v13.10.0'
  /usr/bin/docker pull w9jds/firebase-action:v13.10.0
  Error response from daemon: manifest for w9jds/firebase-action:v13.10.0 not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 7.39 seconds before retry.
  /usr/bin/docker pull w9jds/firebase-action:v13.10.0
  Error response from daemon: manifest for w9jds/firebase-action:v13.10.0 not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 4.127 seconds before retry.
  /usr/bin/docker pull w9jds/firebase-action:v13.10.0
  Error response from daemon: manifest for w9jds/firebase-action:v13.10.0 not found: manifest unknown: manifest unknown
Error: Docker pull failed with exit code 1```

Is it possible to disable this version bump?

**Comment by catalystStephen** [comment]
#me2

**Comment by w9jds** [comment]
I'm working on a fix it got closer to working but failed at the final step this time.

**Comment by pinchy** [comment]
Thanks @w9jds , I appreciate the attention you're giving this. The repo is super useful to us here (which is why we find out pretty quick when something goes down as we use it constantly!)

**Comment by w9jds** [comment]
Here is the last job, as you can see it almost got it working, I just had an issue with passing outputs between stages. https://github.com/w9jds/firebase-action/actions/runs/9183135041

I pushed another update to the action that handles auto bumping, so hopefully the next bump should work as expected.

**Comment by Zinoka** [comment]
Hello @w9jds,
Do you have some news about the manifest error ?

**Comment by pinchy** [comment]
Failed again for the latest version bump.
<img width="1114" alt="Screenshot 2024-05-29 at 8 00 37 PM" src="https://github.com/w9jds/firebase-action/assets/1025321/b443a814-fc38-4e89-b8e1-c9d3a947f3c8">


Is it possible to kill the version bump bot? We all love the codebase, and I feel awkward having to report the same bug each week, makes it tricky for you to maintain!

**Comment by w9jds** [comment]
Again, I'm working on a fix. Each version is helping me catch and fix things. I believe the next one should work, docker was rejected some tagging and pushes.

**Comment by pinchy** [comment]
Alas it failed again. :(
Maybe it's easier if we disable/remove the bot please? Maybe a few of us can fork it without the bot?

**Comment by w9jds** [comment]
As stated in the README if you want to keep a specific version you can specify the version of the action you want to use. Using Master is always a risky move (you can also use the setup-firebase action I created which is faster and way more customizable). I have successfully fixed the auto bumping action though, I went ahead and just kept reverting the changes and triggering the action until I got the docker issues fixed (I am looking into it possibly not publishing the new firebase-tools, but it won't not find the image anymore)
