### ISSUE TITLE
Image for v13.23.0 missing

### ISSUE THREAD

**Issue by dedayoa** [w9jds/firebase-action#242]
The image for v13.23.0 is missing. I also can't find it in the github packages list.

![image](https://github.com/user-attachments/assets/2b32d94b-0383-4956-9055-e8cc1be69bfc)

**Comment by go-nagai** [comment]
Same here...

**Comment by augustoximenes** [comment]
Me too!

**Comment by YoheyFunada** [comment]
Me too!

**Comment by neofrigate** [comment]
same here!

**Comment by itoga** [comment]
I replaced `uses: w9jds/firebase-action@master` with `uses: docker://w9jds/firebase-action:master`, and it worked.

**Comment by dedayoa** [comment]
You can also pin to a specific version e.g 
`uses: w9jds/firebase-action@v13.22.1`...which is the way to go for your production use.

**Comment by w9jds** [comment]
Apologies for the delay everyone! I re-ran the job looks like docker had a hick-up from me pushing. The image should be there now.
