### ISSUE TITLE
How to work with this secret.FIREBASE_TOKEN in angular

### ISSUE THREAD

**Issue by MoutPessemier** [w9jds/firebase-action#25]
I'm using angular to make and firebase to host my website and I've got my login token but I wouldn't know where to put it. I was thinking that the `secret.FIREBASE_TOKEN` looks like some sort of env file but I don't understand how he can read that file since it contains secrets and you don't want to upload such a file right?

**Comment by w9jds** [comment]
Secrets are a system used inside of Github: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets

**Comment by MoutPessemier** [comment]
Thanks a lot!
