### ISSUE TITLE
Fetching config variables when deploying Firebase Functions

### ISSUE THREAD

**Issue by glocore** [w9jds/firebase-action#29]
The [Firebase docs](https://firebase.google.com/docs/functions/local-emulator#set_up_functions_configuration_optional) suggests downloading config variables using this command:
```shell
firebase functions:config:get > .runtimeconfig.json
```
This allows accessing the config variables inside JavaScript using `functions.config()`

I was wondering if and how this command can be run using this action?

Thanks!

**Comment by w9jds** [comment]
Currently the action doesn't support this kind of behavior, though it is absolutely possible. I didn't realize they had added this functionality and have always set these configurations by hand. I'll look into it and see if I can add it for you.

**Comment by akshaykay** [comment]
@glocore Would you mind sharing the entire workflow yaml file?

**Comment by microchipgnu** [comment]
Sorry for re-opening. Is this in the plans?

**Comment by microchipgnu** [comment]
Sorry for commenting in here. Is this in the plans?
