### ISSUE TITLE
eslint not detected

### ISSUE THREAD

**Issue by CaineLloyd** [w9jds/firebase-action#30]
Hello! I am having an issue with the deploy, it seems as though the linting script that normally comes with Firebase is not functioning or not being detected, during the deploy I receive the following errors.

I have updated npm, ran npm install in the functions folder, and manually reinstalled lint. Lint was also successfully automatically installed originally with firebase init.

```
i  deploying database, storage, firestore, functions, hosting
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint /github/workspace/functions
> eslint .

sh: 1: eslint: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! functions@ lint: `eslint .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the functions@ lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /github/home/.npm/_logs/2020-03-13T04_57_55_951Z-debug.log

Error: functions predeploy error: Command terminated with non-zero exit code1
```

**Comment by w9jds** [comment]
More information is going to be needed, as from what I understand firebase-tools has a build in check, but I don't think it ships with eslint itself. So there is probably something related to the build of you container that is causing the issue.

**Comment by rossanmol** [comment]
Same issue here, but with `tslint`. Firebase runs lint on deploy :(

**Comment by jczacharia** [comment]
This might lead to a solution.

https://github.com/firebase/firebase-tools/issues/610

**Comment by w9jds** [comment]
Yes, make sure you have updates your firebase.json like listed in the issue on `firebase-tools` I updated that a long time ago and my deploys don't seem to have any issues.

**Comment by wtfiwtz** [comment]
I think the issue is `pre-deploy` occurs in a different directory to the build. Ensure you have `eslint` and `tsc` in your `package.json` and update `firebase.json` to something like this (compatible with Linux, Mac and Windows):

```
{
  "functions": {
    "predeploy": [
      "npm --prefix ./functions/ install",
      "npm --prefix ./functions/ run lint",
      "npm --prefix ./functions/ run build"
    ],
    "source": "functions"
  }
}
```

If you don't want the linter to fail your build, remove the `run lint` line above as well :)

Cheers,
Nigel
