### ISSUE TITLE
Can't add message (-m) to deploy command

### ISSUE THREAD

**Issue by miroo93** [w9jds/firebase-action#31]
Hi,
I am trying to add a message to the firebase deploy command as described in [firebase doc](https://firebase.google.com/docs/cli#deployment):
```
uses: w9jds/firebase-action@master
      with:
        args: deploy -m "${{env.CI_FIREBASE_MESSAGE}}"
```
When running the pipeline, I am getting this error:

> Error: Too many arguments. Run firebase help deploy for usage instructions
![image](https://user-images.githubusercontent.com/2525167/76657872-34bc6000-6549-11ea-97e9-54d7d7cc2a0b.png)

Should you add that as part of a new action environment variable?

Thank you

**Comment by w9jds** [comment]
The way the action works is it places the arguments you put in the config directly into the `firebase-tools` cli. If you are getting errors, then you aren't providing something that it can use. I do not see in the github actions documentation that you can use environment variables like that: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#env

**Comment by miroo93** [comment]
Sorry, with all due respect, could you please try on your own and see if adding a message for the deploy command works?
I just tried again without any environment variable (which is btw completely fine the way I defined it, it's just a formatted text I'm defining in the "env" section), and it still doesn't work.

So even with hard-coding a message it would give the exact same error:
```
uses: w9jds/firebase-action@master
      with:
        args: deploy -m "hard coded message"
```
Thanks again

**Comment by w9jds** [comment]
With the way that yaml works and how it is passed into docker you need to escape your `"` so it needs to be `deploy -m \"${{env.CI_FIREBASE_MESSAGE}}\"`

**Comment by miroo93** [comment]
Yep, that was it.
Thank you!
