### ISSUE TITLE
For some reason, this action always gets rebuilt every time it runs

### ISSUE THREAD

**Issue by treeder** [w9jds/firebase-action#32]
And it takes ~44 seconds every time to do it. Is there some way to make this prebuilt like most other actions?

![image](https://user-images.githubusercontent.com/75826/77757431-9d0a4780-7007-11ea-85b5-3901cb640695.png)

That build step is not part of my workflow, it just does it automatically every time probably so it can be used later on.

**Comment by w9jds** [comment]
This is a docker action, which means it builds the docker container whenever it is used. I can look into documentation to see if they added a caching system, but this is just how docker actions work.

**Comment by treeder** [comment]
Ahh, ok. I'll close for now and maybe we can revisit once they add support for this.
