### ISSUE TITLE
Preprend cross-env NODE_ENV=production

### ISSUE THREAD

**Issue by 5tormTrooper** [w9jds/firebase-action#33]
As part of my package.json, my deploy script looks like this:
```
"deploy": "cross-env NODE_ENV=production firebase deploy --only functions,hosting"
```
Without the `cross-env NODE_ENV=production`, my deployed app doesn't work.
With just `args: deploy --only functions,hosting` in the workflow, I get this error during the deploy:
<img width="1316" alt="Image 2020-03-31 at 2 26 59 PM" src="https://user-images.githubusercontent.com/4154407/78045546-5e152280-7376-11ea-9e69-b1aee0fe97b5.png">

I have `"main": "dist/server/index.js"` set in package.json, and if I download the build zip, that file does exist. Not sure what I'm doing wrong here.

Is it possible to prepend `cross-env NODE_ENV=production` before firebase deploy?

I should note that I also tried `args: deploy --only functions,hosting:production` and got the same error.

**Comment by w9jds** [comment]
I don't know why you would prepend `firebase` there is no point. If you are deploying hosting the build should be done in another step, if you are doing functions, then you need to update your `firebase.json` pre-deploy to use the proper script that you are prepending an environment variable to. If your Firebase is configured for functions and hosting then you don't need to supply `--only` you just need `deploy`.

**Comment by 5tormTrooper** [comment]
I'm going to see if I can set the env var a different way, but in any case, this seems like a config issue rather than something to do with firebase-action. Thanks for the response.

**Comment by SrividyaKK** [comment]
> I'm going to see if I can set the env var a different way, but in any case, this seems like a config issue rather than something to do with firebase-action. Thanks for the response.

Were you able to solve this issue? 
"deploy": "cross-env PROJ_MODE=dev firebase deploy --only functions" doesn't work for me, whereas 
"deploy": "firebase deploy --only functions" does. But obviously, the intended env var wouldn't be set, which would cause my app to break.
