### ISSUE TITLE
The action has stopped working

### ISSUE THREAD

**Issue by Seanitzel** [w9jds/firebase-action#35]
I have been using this action in multiple repositories.

Since yesterday(4/16/20) it does not work anymore and fail with the following error:

```Error: An unexpected error has occurred.```

It fails on multiple repositories where no configuration has been changed, so i believe it isn't related to issue #23 .

**Comment by w9jds** [comment]
Interesting, I haven't updated the action. What version are you pointing your actions at?

**Comment by Seanitzel** [comment]
Yea it is really weird,

I'm pointing it to the master branch.

My yml file is exactly the same as in the docs, and there were no changes to my environment, could it be something internal?

**Comment by w9jds** [comment]
Every time it runs, it pulls the latest version of `firebase-tools` and builds the docker image. There could be a possibility that `firebase-tools` changed how it works. I would also recommend checking to make sure you supplied token is still valid.

**Comment by Seanitzel** [comment]
Just tried with a new token, same error...

**Comment by Seanitzel** [comment]
You were right, just looked at their changelog, they release version 8.1 yesterday with a bug and they just released a fix in version 8.1.1 30 mins ago 😆

**Comment by hello-consumer** [comment]
I just set this up on a repository today (4/18/2020) and I'm able to use it without issue. I'm doing something slightly different in my YML file (building a react app, then deploying to firebase) than the example documentation, but I don't think that would affect the action execution.

**Comment by w9jds** [comment]
Correct, once they fixed the issue it should have started working again. I will close this issue.
