### ISSUE TITLE
Warning "Unexpected input 'args', valid inputs are ['']"

### ISSUE THREAD

**Issue by colecrtr** [w9jds/firebase-action#42]
Just recently started showing up: https://github.com/colecrtr/doozle/runs/702762862?check_suite_focus=true#step:7:1

I don't believe I changed anything related to that action recently.

**Comment by salozord** [comment]
Having the same issue here 🤔. Maybe this can be somewhat the reason (?):
[https://github.com/actions/runner/issues/499](https://github.com/actions/runner/issues/499)

**Comment by w9jds** [comment]
Not so sure about that, this is a Docker action arguments are tunneled directly to the shell command from the docker images. I was more inclined to think this was a CLI change as the latest version of the CLI is pulled each time the action is run.

If you look at your older runs, can you see what version npm installed versus the one that prints out now?

**Comment by mg-myoxygen** [comment]
Not sure what version of npm is from the logs (node seems to be 10-slim both before and after I started getting these warning messages), but the Actions runner version changed from "2.169.1" to "2.262.1".

Seems it's not the only bug introduced during that change: https://github.com/actions/runner/issues/503 ?

**Comment by salozord** [comment]
Yes, I have the same `node 10-slim` version(before and after) and the update on the Actions runner version 🤔. I agree with @mg-myoxygen with the fact that it may be a bug on the runner.

**Comment by w9jds** [comment]
This is no longer using node 10-slim and I don't see any new information on this. So unless you keep seeing this and think it is related to this action I'm going to close it.

**Comment by mg-myoxygen** [comment]
Yup, thanks @w9jds! Just a note that it seems to have been fixed for me when they updated the Action runner from 2.262.1 to 2.263.0 .
