### ISSUE TITLE
How to setup release 

### ISSUE THREAD

**Issue by SuperHuman12** [w9jds/firebase-action#50]
@w9jds @torbjornvatn @uphy @grennis @itwasmattgregg 

Hey guys, do you know how can this worker file be used to only publish only releases ?
I am trying to manage my app based on versions, like every release version that i create to then to auomatically deployed to firebase.

**Comment by itwasmattgregg** [comment]
If I were you I would do this with the way I set up my github branches. Make separate release branches off of master and merge into master when you’re ready to release. Master should usually reflect what is deployed to production.

**Comment by SuperHuman12** [comment]
@itwasmattgregg Hey Matt 

As I release multiple versions each day, The problem is if the version that is released starts giving out problems .

I should be able to revert back, how would you do if that were the case ?

**Comment by itwasmattgregg** [comment]
Again this all just has to do with your git strategy. If you’re worried about releasing bad code I might set up a test environment alongside your production one. Merge releases into staging for testing before pushing to actual production. If you need to revert you can always do that by reverting your releases merge commit which will trigger a build. 

You should do some research on different git release strategies and close this issue as it’s not really an issue with the code. Good luck

**Comment by SuperHuman12** [comment]
this was helpful , thanks
