### ISSUE TITLE
My styles are not being deployed when I use this function.

### ISSUE THREAD

**Issue by akshay-nm** [w9jds/firebase-action#54]
I have a project bootstrapped from create-react-app. I have setup tailwindcss with postcss-cli. 
I have tested that everything works on my local machine. When I use the `firebase deploy --only hosting` from my local machine, everything works perfectly. 
When I use the code mentioned in the github action description, no styles are deployed and the site looks broken.

**Comment by w9jds** [comment]
This is probably related to where your styles are located in your project, and the previous build steps to the deployment. All this action does is takes the build from previous steps and runs the deploy. If those files aren't there, then it can't deploy them.

**Comment by akshay-nm** [comment]
I am using this as my workflow:
`
​name​: ​Build and Deploy​
​on​:
  ​push​:
    ​branches​:
      - ​master​

​jobs​:
  ​build​:
    ​name​: ​Build​
    ​runs-on​: ​ubuntu-latest
    env:
        REACT_APP_FIREBASE_CONFIG_VARIABLES: {{ secrets.SECRET_VARIABLES }}
        ...
    ​steps​:
      - ​name​: ​Checkout Repo​
        ​uses​: ​actions/checkout@master​
      - ​name​: ​Install Dependencies​
        ​run​: ​yarn
      - ​name​: ​Build​
        ​run​: ​yarn build
      - ​name​: ​Archive Production Artifact​
        ​uses​: ​actions/upload-artifact@master​
        ​with​:
          ​name​: ​dist​
          ​path: build
  ​deploy​:
    ​name​: ​Deploy​
    ​needs​: ​build​
    ​runs-on​: ​ubuntu-latest​
    ​steps​:
      - ​name​: ​Checkout Repo​
        ​uses​: ​actions/checkout@master​
      - ​name​: ​Download Artifact​
        ​uses​: ​actions/download-artifact@master​
        ​with​:
          ​name​: ​dist​
          ​path​: ​build
      - ​name​: ​Deploy to Firebase​
        ​uses​: ​w9jds/firebase-action@master​
        ​with​:
          ​args​: ​deploy --only hosting​
        ​env​:
          ​FIREBASE_TOKEN​: ​${{ secrets.FIREBASE_TOKEN }}
`

**Comment by w9jds** [comment]
Yeah, so this isn't related to the action. This just runs the CLI in a docker container, if the workflow doesn't properly have all the files in that container, then it can't deploy them. Without seeing the entire setup, I can't say what it is. However, this usually happens when either the styles are at the root, or not properly copied into the build when it artifacts.

**Comment by akshay-nm** [comment]
Okay, I'll try to find what's causing this. Since it's probably not related to the action, closing this one.

**Comment by akshay-nm** [comment]
This has something to do with how postcss and tailwindcss are configured. 
I switched back to `tailwindcss` command to build styles in prebuild step and everything started working normally. 
I guess there are some breaking changes in tailwindcss.
I'll update this comment with a solution if I find one.
