### ISSUE TITLE
Deploy to Firebase fails: Error: An unexpected error has occurred.

### ISSUE THREAD

**Issue by sansan88** [w9jds/firebase-action#55]
**Error Message**

Deploy to Firebase

Error: An unexpected error has occurred.

Run w9jds/firebase-action@master

/usr/bin/docker run --name cbc08e7a8c8ada4ddcacce4cf2ae5cf190_8fac18 --label 8118cb --workdir /github/workspace --rm -e FIREBASE_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/myclub-app/myclub-app":"/github/workspace" 8118cb:c08e7a8c8ada4ddcacce4cf2ae5cf190 deploy --only hosting

Error: An unexpected error has occurred

**Solution**
If you have multiple hosting destinations, the deployment fails. so make sure, your .firebaserc & firebase.json file has just one destination for hosting.

**Comment by neospirit** [comment]
Same issue here

**Comment by ronaldohoch** [comment]
The solution shown by @sansan88 works!
I had have removed the functions object from firebase.json file.
