### ISSUE TITLE
Provide a tag so I don't have to build from master on every deploy

### ISSUE THREAD

**Issue by mjackson** [w9jds/firebase-action#57]
It'd be nice to have a tag to pull from instead of pulling and building from master on every build. On average my builds take 40-50 seconds to build the firebase action.

Is this possible? I know there are some other actions that I use that I don't have to build every time (actions/checkout, for example), but I've never published a GitHub Action myself so I'm not sure how to do it.

**Comment by w9jds** [comment]
Sadly, there are two different kind of actions. Docker and Javascript/Typescript, the docker actions pull the image and build it each time (as docker usually does). Where as Javascript and Typescript it just pulls and runs the code, (so it tends to be much faster).

**Comment by mjackson** [comment]
Thanks for the reply. Sounds like it'd require you to rewrite the action in JavaScript. I'll go ahead and close. Maybe I can just `npm install firebase-tools` and use that directly...
