### ISSUE TITLE
Cant deploy to other enviroment than default

### ISSUE THREAD

**Issue by andirsun** [w9jds/firebase-action#59]
/usr/bin/docker run --name aac2aa809a24076cc543209e911edae508de18_f604d4 --label aac2aa --workdir /github/workspace --rm -e FIREBASE_TOKEN -e INPUT_ARGS -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/landing/landing":"/github/workspace" aac2aa:809a24076cc543209e911edae508de18 deploy --only hosting:development
```
Error: No project active, but project aliases are available.

Run firebase use <alias> with one of these options:

  default (tingo-landing)
  development (tingo-landing-dev)
```

**Comment by tlarrain** [comment]
in the ``args`` you can use:

`` deploy --only hosting --project development``

**Comment by andirsun** [comment]
> in the `args` you can use:
> 
> ` deploy --only hosting --project development`

I solved with 
```
deploy -P development --only hosting
```
But would be nice to update the readme

**Comment by w9jds** [comment]
I'm going to close this, as this is general `firebase-cli` commands, nothing specific to the action for doing this. 

Thank you for the information!
