### ISSUE TITLE
Prebuild Docker image to save time and resources

### ISSUE THREAD

**Issue by Sturgelose** [w9jds/firebase-action#64]
This action does the build every time of the docker image and installs firebase from NPM, which takes around ~1 min every time.
Wouldn't it make sense to prebuild the docker image in this repo and directly use the docker image depending on the desired firebase version?

This will reduce the amount of time pulling from NPMJS and building the image, and also the costs if you are paying for GithubActions credits.

Now the question is how to track updates in firebase repo/firebase NPMJS repo to update the Docker image....

**Comment by w9jds** [comment]
That isn't how Github Actions work, they pull the DockerFile and build it on each use. That is just how the docker actions work.
