### ISSUE TITLE
Why does it always build the image?

### ISSUE THREAD

**Issue by rai-codekaust** [w9jds/firebase-action#67]
I have used this action to deploy my React App to firebase. 
Each time the workflow runs, the docker image is created from the Dockerfile.

This really takes up time in the Github action.
Why is the docker image is not just pulled from dockerhub (or elsewhere)?

**Comment by rai-codekaust** [comment]
Seems like pushing this action to docker-hub should solve the issue. Can we do that?
Resource: https://github.community/t/docker-action-uses-build-instead-of-pull/17963

This will really bring down the time-penalty of the build action.

**Comment by Hacksore** [comment]
@rai-codekaust After thinking about this you have to consider that the one benefit that the building gives you is the latest `firebase-tools` version.

If it is a baked image it'd have to be maintained so the cli can be updated as well. I did open #68 so that we have a version that is baked but we'll have to see what @w9jds thinks.

I did also see you [forked this repo](https://github.com/rephraseai/firebase-action) and did just that so maybe you can offer your experience during the usage.

**Comment by Hacksore** [comment]
So #68 pretty much solved this but could still be improvements.

I actually read this, might make more sense. Attach a hook onto `firebase-tools` updates and have it kick off a build jobs.

https://blog.npmjs.org/post/145260155635/introducing-hooks-get-notifications-of-npm

**Comment by w9jds** [comment]
Yeah, I was looking at this last night. I set up a couple hooks to notify on me on github releases but I also looked into this, I will probably implement something to do this, or someone might do it before me.

**Comment by codekaust** [comment]
> @rai-codekaust After thinking about this more you have to consider that the one benefit that the building gives you is the latest `firebase-tools` version.
> 
> If it is a baked image it'd have to be maintained so the cli can be updated as well. I did open #68 so that we have a version that is baked but we'll have to see what @w9jds thinks.
> 
> I did also see you [forked this repo](https://github.com/rephraseai/firebase-action) and did just that so maybe you can offer your experience during the usage.

Hey, I actually hosted its image publically on Dockerhub.
Check this out: https://github.com/rephraseai/firebase-action/blob/f062f217973df4244451890859264c096464a51b/action.yaml#L9

**Comment by Hacksore** [comment]
@codekaust If you use `w9jds/firebase-action@master` not it will pull instead of build 😎

**Comment by rai-codekaust** [comment]
Amazing! Thanks. This is very helpful.

**Comment by w9jds** [comment]
Sure thing! Thank @Hacksore I modified his approach. It also include JDK now so emulators work as well, was avoiding putting it in because it increased the build time a lot.
