### ISSUE TITLE
Unable to use firebase emulator as java version is too low.

### ISSUE THREAD

**Issue by danieljimeneznz** [w9jds/firebase-action#70]
I saw that you recently added jdk7 to allow the use of the emulator but when I run the emulator in my Github action I get:

```
firestore: Unsupported java version, make sure java --version reports 1.8 or higher.
```

And their documentation recommends Java 8. (https://firebase.google.com/docs/emulator-suite/install_and_configure).
I'm more than happy to open a PR for this change but wanted to check with you first to make sure that Java 7, wasn't chosen for any specific reason? (i.e. I know firebase has been working in this area so unsure if they recently made the change to Java 8).

**Comment by w9jds** [comment]
No, I used 7 because that is what it used to require, I must have missed the update to 8 recently.

**Comment by w9jds** [comment]
Could you give it a try again, I released a new docker image that should fix this for you.

**Comment by danieljimeneznz** [comment]
Yup I can confirm this works.
