### ISSUE TITLE
Where will I get my FIREBASE_TOKEN?

### ISSUE THREAD

**Issue by 96312** [w9jds/firebase-action#73]
Apologies, I'm just getting started with Github Actions and wanted to use this workflow. Where exactly can I find the FIREBASE_TOKEN or GCP_SA_KEY?

My dashboard in firebase is showing a project number. Also, do I have the save the same as an ENV file before pushing? 

Please and thank you for your help.

---

update: Hello, I found the FIREBASE_TOKEN but can't figure out where to save it.

**Comment by 96312** [comment]
Closing this cuz I figured everything out on my own.

**Comment by nerdophile** [comment]
@96312 How did you fix it?  I am facing the same issue
