### ISSUE TITLE
Setting PROJECT_PATH did not work

### ISSUE THREAD

**Issue by grennis** [w9jds/firebase-action#9]
My entire firebase project is in a subdirectory under the root.

I set `PROJECT_PATH` variable correctly, but I still got the error: `Error: firebase use must be run from a Firebase project directory.`

I noticed that in `entrypoint.sh`, the call to `firebase use ...` occurs before the call to `cd $PROJECT_PATH`. I think the order of the two should be switched.

I'm happy to submit PR if this is indeed the problem, or let me know if I am missing something. Thanks!

**Comment by peter-evans** [comment]
That's my bad, sorry about that! I submitted [this PR](https://github.com/w9jds/firebase-action/pull/8) just recently to add `PROJECT_PATH`. I'm sure you are correct that they should be switched.

I would go ahead and a send a PR to switch the order.

**Comment by grennis** [comment]
Great, will do
